import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

import { STATUSES } from "../../src/schema.ts";
import { toneOf } from "../src/posting.ts";

const UI = join(import.meta.dirname, "..");

function cssClasses(): Set<string> {
  // Comments and url(...) values stripped: a name cited in prose, or the
  // dots in a data-URI SVG, are not selectors.
  const css = readFileSync(join(UI, "app.css"), "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/url\([^)]*\)/g, "url()");
  return new Set([...css.matchAll(/\.([a-z][a-z0-9-]*)/g)].map((match) => match[1] ?? ""));
}

/**
 * Every word inside a `template:` literal in `ui/src`, plus the tone
 * classes: a `'tone-' + toneOf(...)` binding leaves `tone-` in the template
 * but not `tone-progress`, so each status's tone is added by hand.
 */
function templateWords(): Set<string> {
  const words = new Set<string>();
  for (const name of readdirSync(join(UI, "src"))) {
    const source = readFileSync(join(UI, "src", name), "utf8");
    for (const block of source.matchAll(/template: `([\s\S]*?)`,/g)) {
      for (const word of (block[1] ?? "").matchAll(/[a-z][a-z0-9-]*/g)) words.add(word[0]);
    }
  }
  for (const status of STATUSES) words.add(`tone-${toneOf(status)}`);
  // Generated by Vue's `TransitionGroup name="list"` from the `name`
  // attribute, never written literally in any template.
  for (const cls of [
    "list-move",
    "list-enter-active",
    "list-enter-from",
    "list-leave-active",
    "list-leave-to",
  ]) {
    words.add(cls);
  }
  return words;
}

test("every class app.css styles is one some template renders", () => {
  const rendered = templateWords();
  const dead = [...cssClasses()].filter((name) => !rendered.has(name)).sort();
  assert.deepEqual(dead, []);
});
