// The place names behind the "United States only" rule. One set of names
// for both criteria (`country` in listing.ts reads the label,
// `country_restriction` in text.ts the body): a name on one list and
// missing from the other would let the same posting read as foreign by its
// label and domestic by its text. In code, not the criteria row, since the
// world's country names are not James's to set.
//
// The United States list can afford to be loose: it is consulted only after
// a foreign name has matched, and only ever to keep a posting. A false hit
// there costs one glance; a false hit on the foreign list loses a role.

function escapeRegExp(term: string): string {
  return term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// A term written in capitals is an acronym and matches only in capitals;
// otherwise "US" matches the pronoun and "EU", "IN" and "OK" match
// ordinary words.
function patternFor(term: string): RegExp {
  const isAcronym = term === term.toUpperCase() && /[A-Z]/.test(term);
  return new RegExp(`\\b${escapeRegExp(term)}\\b`, isAcronym ? "" : "i");
}

// "U.S." and "U.S.A." are "US" and "USA" once the dots go, and no name
// below carries one. `\b` will not close a match on a trailing ".".
function normalize(text: string): string {
  return text.replace(/\./g, "");
}

// Countries and the multi-country regions that exclude the United States.
// Names a US place shares are handled by the United States list winning
// (see `unitedStatesPlace`): "Mexico, MO", "Lebanon, NH", "Peru, IN" all
// name a state too. "Georgia" is left off entirely: a US state shares it
// exactly. Cities are absent: "Dublin", "Paris", "Lima" and "Toledo" are
// US cities too, and a city-only label falls to "names no country is in".
const COUNTRY_TERMS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Congo",
  "Denmark",
  "Dominican Republic",
  "Dominica",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Equatorial Guinea",
  "Papua New Guinea",
  "Guinea",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Northern Ireland",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Holland",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "Niger",
  "North Korea",
  "South Korea",
  "Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Trinidad",
  "Tunisia",
  "Türkiye",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "UAE",
  "United Kingdom",
  "Great Britain",
  "Britain",
  "England",
  "Scotland",
  "Wales",
  "UK",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Viet Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

// Regions with the United States in none of them; "Americas", "North
// America", "AMER" and "NAMER" include it and live on the other list.
// Ordered specific-first so the reason quotes the fuller name.
const FOREIGN_REGION_TERMS = [
  "European Union",
  "European",
  "Europe",
  "EMEA",
  "EU",
  "Asia Pacific",
  "Asia-Pacific",
  "Southeast Asia",
  "South Asia",
  "Asia",
  "APAC",
  "Latin America",
  "South America",
  "Central America",
  "LATAM",
  "Middle East",
  "MENA",
  "North Africa",
  "Sub-Saharan Africa",
  "Africa",
  "Oceania",
  "ANZ",
  "DACH",
  "Benelux",
  "Nordics",
  "Scandinavia",
  "Caribbean",
] as const;

const US_STATE_NAMES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "West Virginia",
  "Virginia",
  "Washington",
  "Wisconsin",
  "Wyoming",
  "District of Columbia",
  "Puerto Rico",
] as const;

const US_STATE_ABBREVIATIONS = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "DC",
] as const;

// Every spelling that puts the United States inside the posting's reach.
// "New England" is here because "England" sits inside it. A state's name or
// postal abbreviation counts: it is what rescues "Mexico, MO" from the
// country list.
const UNITED_STATES_TERMS = [
  "United States of America",
  "United States",
  "USA",
  "US",
  "North America",
  "Americas",
  "NORAM",
  "NAMER",
  "AMER",
  "New England",
  ...US_STATE_NAMES,
  ...US_STATE_ABBREVIATIONS,
] as const;

const FOREIGN_PATTERNS: readonly (readonly [string, RegExp])[] = [
  ...COUNTRY_TERMS,
  ...FOREIGN_REGION_TERMS,
].map((term) => [term, patternFor(term)] as const);

const UNITED_STATES_PATTERNS: readonly (readonly [string, RegExp])[] = UNITED_STATES_TERMS.map(
  (term) => [term, patternFor(term)] as const,
);

function firstMatch(text: string, patterns: readonly (readonly [string, RegExp])[]): string | null {
  const normalized = normalize(text);
  for (const [term, pattern] of patterns) {
    if (pattern.test(normalized)) return term;
  }
  return null;
}

// Null is the design's default case, "a posting that names no country is
// in", not an error.
export function foreignPlace(text: string): string | null {
  return firstMatch(text, FOREIGN_PATTERNS);
}

// A text naming both ("Remote US & Canada") is in, so a foreign match is
// checked against this rather than overturned by it.
export function unitedStatesPlace(text: string): string | null {
  return firstMatch(text, UNITED_STATES_PATTERNS);
}
