-- Migration 20260908000000_init: the schema as it stood at first apply.
-- Generated by scripts/gen-schema.ts; regenerate it and db/schema.sql
-- together (tests/migrate-schema.test.ts fails when they disagree).
--
-- The Supabase CLI applies this file: `supabase db reset` locally,
-- `supabase db push` to a linked project. Do not paste it by hand.
--
-- TWO TABLES TRACK MIGRATIONS AND THAT IS DELIBERATE.
-- supabase_migrations.schema_migrations is the CLI's; it owns applying and
-- ordering, and PostgREST does not expose that schema, so the running
-- application cannot read it. The public schema_migrations table this file
-- creates is the receipt the application DOES read: src/store/migrations.ts
-- compares it against the files on disk and `doctor` refuses on any
-- disagreement. The last statement below is this file recording itself, so
-- applying and recording are one file and cannot come apart.
--
-- Every LATER migration is hand-written and is not generated from
-- src/schema.ts, and must end with its own INSERT the same way.
-- `supabase db reset` is what proves the deltas add up: it replays every
-- migration into an empty Postgres. Compare a new one against the diff
-- db/schema.sql shows when it is regenerated.

CREATE TABLE IF NOT EXISTS "events" (
  "id" text PRIMARY KEY,
  "key" text NOT NULL,
  "kind" text NOT NULL CHECK ("kind" IN ('seen', 'decide')),
  "run_id" text,
  "at" timestamptz NOT NULL,
  "by" text CHECK ("by" IN ('model', 'operator', 'legacy')),
  "stage" text CHECK ("stage" IN ('silenced', 'in_pipeline', 'employer_ruled_out', 'non_us', 'below_floor', 'title', 'candidate')),
  "verdict" text CHECK ("verdict" IN ('ADD', 'REJECT', 'NEEDS_MORE', 'CLOSE', 'ACTIVATE', 'REGRADE', 'RESCORE', 'KEEP', 'CONFIRM', 'REVERT', 'EDIT', 'DEFER')),
  "reason" text,
  "row" jsonb,
  "evidence" jsonb
);

CREATE INDEX IF NOT EXISTS "events_key_at_idx" ON "events" ("key", "at");

-- One row per posting ever fetched; the engine upserts it on every
-- sighting, so `last_seen` moves and `first_seen` stays.
CREATE TABLE IF NOT EXISTS "jobs" (
  "key" text PRIMARY KEY,
  "company" text NOT NULL,
  "platform" text CHECK ("platform" IN ('greenhouse', 'ashby', 'lever', 'workday', 'eightfold', 'smartrecruiters', 'amazon')),
  "board" text,
  "source" text,
  "title" text,
  "url" text,
  "location" text,
  "geo" text CHECK ("geo" IN ('us-remote', 'non-us', 'office-anchored', 'unknown')),
  "comp_low" integer,
  "comp_high" integer,
  "updated" text,
  "first_seen" timestamptz NOT NULL,
  "last_seen" timestamptz NOT NULL,
  "last_run_id" text,
  "last_stage" text CHECK ("last_stage" IN ('silenced', 'in_pipeline', 'employer_ruled_out', 'non_us', 'below_floor', 'title', 'candidate'))
);

CREATE INDEX IF NOT EXISTS "jobs_last_seen_idx" ON "jobs" ("last_seen");

-- One row per (job, criteria version): a criteria change re-grades
-- into new rows and the old version's rows stay for `relevance diff`.
CREATE TABLE IF NOT EXISTS "relevance" (
  "id" text PRIMARY KEY,
  "key" text NOT NULL,
  "criteria_version" text NOT NULL,
  "tier" text NOT NULL CHECK ("tier" IN ('out', 'weak', 'possible', 'strong')),
  "reasons" jsonb NOT NULL,
  "graded_at" timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS "relevance_key_idx" ON "relevance" ("key");
CREATE INDEX IF NOT EXISTS "relevance_version_idx" ON "relevance" ("criteria_version");

-- A table, never a view over `events`: PostgREST cannot merge JSONB
-- patches per key in order, which projecting the log through a view
-- would need. `project()` derives it instead; the engine writes it.
CREATE TABLE IF NOT EXISTS "pipeline" (
  "key" text PRIMARY KEY,
  "company" text NOT NULL,
  "role" text,
  "url" text,
  "source" text,
  "comp_low" integer,
  "comp_high" integer,
  "comp_posted" boolean NOT NULL,
  "comp_display" text,
  "remote" boolean,
  "remote_evidence" text,
  "geo_band" text,
  "status" text NOT NULL CHECK ("status" IN ('In Review', 'Active', 'Applied', 'Interviewing', 'Offer Extended', 'Accepted', 'Rejected', 'Closed')),
  "grade" text CHECK ("grade" IN ('marginal', 'good', 'strong')),
  "grade_parts" jsonb NOT NULL DEFAULT '{"comp":null,"stack":null,"domain_avoid":false,"comp_why":null}'::jsonb,
  "days_old" integer,
  "notes" text,
  "first_seen" date NOT NULL,
  "last_verified" date NOT NULL,
  "blocked_on" text,
  "applied_at" date,
  "responded_at" date
);

CREATE TABLE IF NOT EXISTS "employers" (
  "company" text PRIMARY KEY,
  "boards" jsonb NOT NULL,
  "source" text NOT NULL,
  "added" date NOT NULL,
  "disqualified" jsonb,
  "levelFloor" integer,
  "principalIsStaff" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "runs" (
  "run_id" text PRIMARY KEY,
  "date" date NOT NULL,
  "mode" text NOT NULL CHECK ("mode" IN ('interactive', 'scheduled')),
  "status" text NOT NULL CHECK ("status" IN ('complete', 'aborted', 'open')),
  "rubric_version" text NOT NULL,
  "funnel" jsonb NOT NULL,
  "new_reqs_seen" integer NOT NULL,
  "board_errors" jsonb NOT NULL,
  "rejects_audited" integer NOT NULL,
  "rejects_wrongly_rejected" integer NOT NULL,
  "notes" text NOT NULL,
  "at" timestamptz NOT NULL,
  "reason" text,
  "queue_depth" jsonb
);

-- The store's copy of each file under profile/criteria/, one row per
-- version, for the UI to read; the file stays the authority and
-- `criteria sync` reconciles the two.
CREATE TABLE IF NOT EXISTS "criteria" (
  "version" text PRIMARY KEY,
  "status" text NOT NULL CHECK ("status" IN ('pending', 'approved', 'rejected')),
  "derived_at" timestamptz NOT NULL,
  "supersedes" text,
  "profile_hash" text NOT NULL,
  "approved_at" timestamptz,
  "rejected_at" timestamptz,
  "rejected_reason" text,
  "body" jsonb NOT NULL
);

-- One run's worklist — the items the judgment half reads to decide,
-- posting bodies included. One row per (run, posting): the primary key
-- is the derived `<run_id>@<key>`, so a run left open keeps its rows.
-- `fetch` deletes the rows of every run that is `complete` — once
-- `finish` closed it — or `aborted`, which is what bounds the table.
CREATE TABLE IF NOT EXISTS "worklist" (
  "id" text PRIMARY KEY,
  "key" text NOT NULL,
  "run_id" text NOT NULL,
  "company" text NOT NULL,
  "title" text,
  "url" text,
  "location" text,
  "geo" text CHECK ("geo" IN ('us-remote', 'non-us', 'office-anchored', 'unknown')),
  "comp_low" integer,
  "comp_high" integer,
  "days_old" integer,
  "source" text,
  "body" text NOT NULL,
  "kind" text NOT NULL CHECK ("kind" IN ('candidate', 'recheck')),
  "liveness" text CHECK ("liveness" IN ('live', 'gone', 'unknown')),
  "duplicate_of" text,
  "at" timestamptz NOT NULL
);

-- One row per company discovery has ever seen; a re-sight moves
-- `last_seen`, `cards` and `best_comp` and never adds a row. `boards`
-- holds only what the verifier confirmed (src/engine/discovery/
-- discoveries.ts states the contract).
CREATE TABLE IF NOT EXISTS "discoveries" (
  "company" text PRIMARY KEY,
  "channel" text NOT NULL CHECK ("channel" IN ('builtin', 'hn')),
  "best_comp" integer,
  "cards" integer NOT NULL,
  "first_seen" date NOT NULL,
  "last_seen" date NOT NULL,
  "boards" jsonb NOT NULL,
  "probed_at" date,
  "status" text NOT NULL CHECK ("status" IN ('new', 'added', 'rejected')),
  "decided_at" timestamptz,
  "reason" text
);

CREATE TABLE IF NOT EXISTS "schema_migrations" (
  "id" text PRIMARY KEY,
  "applied_at" timestamptz NOT NULL DEFAULT now()
);

-- Row-level security. The service role bypasses RLS by default, so the
-- engine needs no policy; these govern the browser.
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "relevance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pipeline" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "criteria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "worklist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "discoveries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "schema_migrations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_read" ON "events" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "jobs" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "relevance" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "pipeline" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "employers" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "runs" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "criteria" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "worklist" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "discoveries" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON "schema_migrations" FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_write" ON "events" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "authenticated_write" ON "jobs" FOR INSERT TO authenticated WITH CHECK ("source" = 'manual');
CREATE POLICY "authenticated_write" ON "pipeline" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_write" ON "criteria" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_write" ON "employers" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_write" ON "discoveries" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- An RLS policy cannot name columns; column privileges do that.
REVOKE ALL ON TABLE "events" FROM authenticated;
GRANT SELECT, INSERT ON TABLE "events" TO authenticated;
REVOKE ALL ON TABLE "jobs" FROM authenticated;
GRANT SELECT ON TABLE "jobs" TO authenticated;
GRANT INSERT ("key", "company", "source", "title", "url", "location", "comp_low", "comp_high", "first_seen", "last_seen") ON TABLE "jobs" TO authenticated;
REVOKE ALL ON TABLE "relevance" FROM authenticated;
GRANT SELECT ON TABLE "relevance" TO authenticated;
REVOKE ALL ON TABLE "pipeline" FROM authenticated;
GRANT SELECT ON TABLE "pipeline" TO authenticated;
GRANT UPDATE ("status", "notes", "blocked_on", "applied_at", "responded_at") ON TABLE "pipeline" TO authenticated;
REVOKE ALL ON TABLE "employers" FROM authenticated;
GRANT SELECT ON TABLE "employers" TO authenticated;
GRANT UPDATE ("disqualified") ON TABLE "employers" TO authenticated;
REVOKE ALL ON TABLE "runs" FROM authenticated;
GRANT SELECT ON TABLE "runs" TO authenticated;
REVOKE ALL ON TABLE "criteria" FROM authenticated;
GRANT SELECT ON TABLE "criteria" TO authenticated;
GRANT UPDATE ("status", "rejected_at", "rejected_reason") ON TABLE "criteria" TO authenticated;
REVOKE ALL ON TABLE "worklist" FROM authenticated;
GRANT SELECT ON TABLE "worklist" TO authenticated;
REVOKE ALL ON TABLE "discoveries" FROM authenticated;
GRANT SELECT ON TABLE "discoveries" TO authenticated;
GRANT UPDATE ("status", "decided_at", "reason") ON TABLE "discoveries" TO authenticated;
REVOKE ALL ON TABLE "schema_migrations" FROM authenticated;
GRANT SELECT ON TABLE "schema_migrations" TO authenticated;

-- The receipt the application reads. See the header: this is NOT the CLI's
-- own supabase_migrations.schema_migrations, which PostgREST cannot see.
INSERT INTO "schema_migrations" ("id") VALUES ('20260908000000_init');
